# Generated by Django 5.2.12 on 2026-03-18 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_order_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="billed_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="billed_orders", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_type",
            field=models.CharField(choices=[("none", "No Discount"), ("amount", "Fixed Amount"), ("percentage", "Percentage")], default="none", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="final_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunSQL(
            sql="""
            UPDATE orders_order
            SET discount_amount = 0,
                discount_value = 0,
                final_amount = total_amount
            """,
            reverse_sql="""
            UPDATE orders_order
            SET final_amount = total_amount
            """,
        ),
    ]
