# Generated by Django 6.0.3 on 2026-03-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_menu_offer_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='service_station',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('counter', 'Counter')], default='kitchen', max_length=20),
        ),
    ]
