# Generated by Django 6.0.3 on 2026-03-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_offer_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='service_station',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('counter', 'Counter')], default='kitchen', max_length=20),
        ),
    ]
